@u = http://localhost:8080
###
GET {{u}}/app
###
POST {{u}}/app/url
Content-Type: application/json

{
    "url": "www.google.com"
}
###
POST {{u}}/app/url
Content-Type: application/json

{
    "url": "https://google.com"
}
###
POST {{u}}/app/url
Content-Type: application/json

{
    "url": "https://www.zocket.com"
}
###
POST {{u}}/app/url
Content-Type: application/json

{
    "url": "https://www.zocket.com/get-quote"
}
###
# @name shorten
POST {{u}}/app/url
Content-Type: application/json

{
    "url": "https://ifconfig.me"
}

> {%
    const body = response.body;
    const url = body["short-url"];
    const surl = url
    client.global.set("surl",surl)
    const parts = url.split('/');
    const shortCode = parts[parts.length - 1];
    client.global.set("scode", shortCode);

    

%}
###
GET {{surl}}
###
GET {{u}}/app/url/{{scode}}
###
GET {{u}}/admin/urls
###
GET {{u}}/admin/urls?page=2&page_size=1