@u = http://localhost:1422
###
GET {{u}}/app
###
# @name shorten
POST {{u}}/app/url
Content-Type: application/json

{
    "url": "www.google.com"
}

> {%
    const body = response.body;
    const url = body["short-url"];
    const parts = url.split('/');
    const shortCode = parts[parts.length - 1];
    client.global.set("surl", shortCode);
%}
###
GET {{u}}/app/url/{{surl}}